# This file is maintained in https://github.com/davorpatech/meta/
name: Sync repo labels
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/label-sync.yml
  workflow_dispatch:

jobs:
  sync:
    name: Sync repo labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          manifest: .github/labels.yml
